### ISSUE TITLE
Next.js 12 src="[object Object]"

### ISSUE THREAD

**Issue by awgeorge** [remcohaszing/remark-mdx-images#10]
I'm using Next.js 12, although I also tested 13.

When using this remark plugin with the default `npx create-next-app@latest` and following https://nextjs.org/docs/advanced-features/using-mdx, I get the output `<img alt="Image" src="[object Object]">`  meaning the image does not appear.

@michaeloliverx - I notice that you're using Next.js, have you seen this issue?

Thanks for your guidance.
W

**Comment by michaeloliverx** [comment]
> I'm using Next.js 12, although I also tested 13.
> 
> 
> 
> When using this remark plugin with the default `npx create-next-app@latest` and following https://nextjs.org/docs/advanced-features/using-mdx, I get the output `<img alt="Image" src="[object Object]">`  meaning the image does not appear.
> 
> 
> 
> @michaeloliverx - I notice that you're using Next.js, have you seen this issue?
> 
> 
> 
> Thanks for your guidance.
> 
> W

You need to override the img component with Next.js <Image>.

**Comment by awgeorge** [comment]
Thank you sooooooo much.

Replacing `img` with `Image` from `next/image` did indeed do the trick.

```
import { MDXProvider } from '@mdx-js/react'
import Image from 'next/image'

const MDXComponents = {
  img: Image,
}

function MyApp({ Component, pageProps }) {
  return (
    <MDXProvider components={MDXComponents}>
        <Component {...pageProps} />
    </MDXProvider>
  )
}
```
