### ISSUE TITLE
Links support

### ISSUE THREAD

**Issue by robert-orlinski** [remcohaszing/remark-mdx-images#2]
Hi!

This is an awesome tool and could be even more awesome if it would support links. I am not sure if I do not see such a feature but if I am right, there is no easy and clean way to link images added in a relative way.

For instance, this won't work:

```
[![Hierarchy](./hierarchy.jpg)](./hierarchy.jpg)
```

The link points to the parent URL with "hierarchy.jpg" at the end, instead of the image.

Maybe there is or will be a way to accomplish it?

**Comment by remcohaszing** [comment]
Thanks for proposing this! I like the idea. However, after some thinking, I think there might may better solutions. What exactly are you trying to achieve? I feel like this can be solved using [components](https://github.com/wooorm/xdm#components)

If you would like all images to be clickable, you could use the following md(x):

```md
[Hierarchy](./hierarchy.jpg)
```

And define the following component:

```jsx
function MDXImage({ alt, src }) {
  return (
    <a href={src} title={alt}>
      <img alt={alt} src={src} />
    </a>
  )
}

function App() {
  return (
    <MDXProvider components={{ img: MDXImage }}>
      {/* … */}
    </MDXProvider>
  )
}
```

If you would like to use the explicit syntax as you used in your original post, this could be solved using the following custom MDX component instead:

```jsx
function MDXAnchor({ children, ...props }) {
  if(React.Children.count(children) === 1) {
    const child = React.Children.only(children)

    if(child.type === 'img') {
      return (
        <a {...props} href={child.props.src}>{child}</a>
      )
    }
  }
  
  return (
    <a {...props}>{children}</a>
  )
}

function App() {
  return (
    <MDXProvider components={{ a: MDXAnchor }}>
      {/* … */}
    </MDXProvider>
  )
}
```

**Comment by robert-orlinski** [comment]
I wasn't prepared for such an easy answer! Of course, your approach is awesome and completely solves my problem. Thank you!
