### ISSUE TITLE
Cannot get to work with MDX on demand + Next.js

### ISSUE THREAD

**Issue by michaeloliverx** [remcohaszing/remark-mdx-images#4]
I am following the [MDX on demand](https://mdxjs.com/guides/mdx-on-demand/#nextjs-example) guide but struggling to get this plugin to work. I have enabled [`useDynamicImport`](https://mdxjs.com/packages/mdx/#optionsusedynamicimport). Do you have any experience with this? 

```
error loading dynamically imported module
```

**Comment by remcohaszing** [comment]
I don’t have experience with this yet, but maybe it should be possible? Can you share the code causing this issue and a full stack trace?

Also does the issue go away if the MDX doesn’t contain any images?

**Comment by michaeloliverx** [comment]
Hey I played around with this and found a solution that works.

Instead of following the MDX on demand example[^mdx-on-demand] I set up a webpack loader[^nextjs-webpack-loader]. This means that MDX options have to be specified in the `next.config.js` but if you need ESM support this has to be renamed to `next.config.mjs`[^next-config-esm].

[^mdx-on-demand]: https://mdxjs.com/guides/mdx-on-demand/#nextjs-example
[^nextjs-webpack-loader]: https://mdxjs.com/docs/getting-started/#nextjs

### `next.config.mjs`
```js
// @ts-check

import remarkFrontmatter from "remark-frontmatter";
import { remarkMdxFrontmatter } from "remark-mdx-frontmatter";
import { remarkMdxImages } from "remark-mdx-images";

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  experimental: { esmExternals: true },
  pageExtensions: ["mdx", "ts", "tsx"],
  webpack(config, options) {
    config.module.rules.push({
      test: /\.mdx$/,
      use: [
        options.defaultLoaders.babel,
        {
          loader: "@mdx-js/loader",
          /** @type {import('@mdx-js/loader').Options} */
          options: {
            remarkPlugins: [
              remarkFrontmatter,
              [remarkMdxFrontmatter, { name: "frontmatter" }],
              remarkMdxImages,
            ],
          },
        },
      ],
    });

    return config;
  },
};

export default nextConfig;
```

[^next-config-esm]: https://nextjs.org/docs/api-reference/next.config.js/introduction

Then I used a dynamic import with a template string which webpack supports[^webpack-dynamic-expressions-in-import].

[^webpack-dynamic-expressions-in-import]: https://webpack.js.org/api/module-methods/#dynamic-expressions-in-import

Here is a trimmed snippet:

```tsx
import { useState, useEffect } from "react";
import { type MDXModule } from "mdx/types";
import Image from "next/image";

export type Post = {
  slug: string;
  title: string;
  description: string;
};

type Props = {
  post: Post;
};

const mdxComponents = {
  img: (props) => <Image {...props} placeholder="blur" />,
};

export default function BlogPage({ post }: Props) {
  const [mdxModule, setMdxModule] = useState<MDXModule>();
  const Content = mdxModule ? mdxModule.default : null;

  useEffect(() => {
    import(`../../../content/posts/${post.slug}/index.mdx`).then((module) =>
      setMdxModule(module)
    );
    [post.slug];
  });

  return (
    <div>
      <h1>{post.title}</h1>
      {Content ? <Content components={mdxComponents} /> : null}
    </div>
  );
}
```

---

On a side note I really like that your packages use named exports e.g. `remarkMdxImages`/`remarkMdxFrontmatter` rather than the default export AND that the options type is prefixed e.g. `RemarkMdxImagesOptions`/`RemarkMdxFrontmatterOptions`. I think this would be good to have in all the offical unified packages too.

**Comment by remcohaszing** [comment]
Thanks for sharing!
