### ISSUE TITLE
[Feature request] Transform specific frontmatter key(s) into image ESM exports

### ISSUE THREAD

**Issue by michaeloliverx** [remcohaszing/remark-mdx-images#5]
I would like to convert this:
````
```markdown
---
title: "Cool title"
description: "Cool description"
coverImage: "./cool-pic.jpg"
coverImageAlt: "Cool alt"
---
```
````

into something like this:
```
export { default as coverImage } from "./cool-pic.jpg"
```

It has overlap with https://github.com/remcohaszing/remark-mdx-frontmatter. Perhaps it should be another plugin?

**Comment by remcohaszing** [comment]
Thanks for your proposal!

I see why this would be useful. I also see the similarities with `remark-mdx-frontmatter` and `remark-mdx-images`, but I don’t see how it fits in either of them.

I think it’s best to create a separate plugin for this. I imagine something like this?

```js
import { compile } from '@mdx-js/mdx'
import remarkMdxFrontmatterExports from 'remark-mdx-frontmatter-exports'

const { result } = compile(file, {
  remarkPlugins: [
    [remarkMdxFrontmatterExports, { names: ['coverImage'] }]
  ]
})
```

I’m closing this issue as it’s not going to be implemented here.
