### ISSUE TITLE
default export?

### ISSUE THREAD

**Issue by altano** [remcohaszing/remark-mdx-images#6]
It looks like remark guides plugins to have a default export. This plugin doesn't have one.

I'm using some tooling that expects the default export and makes this package unusable. I'm trying to understand and I guess a default export either wasn't always required or it doesn't matter when you're directly controlling what you pass to `.use()`, but it might be a good idea to switch to that.

Would you accept a PR that either adds a default export and bumps the major version #, or one that adds the default export without removing the existing one?

**Comment by remcohaszing** [comment]
Thanks for your suggestion.

As you can see in [here](https://github.com/remcohaszing/remark-mdx-frontmatter/releases), I recently changed `remark-mdx-frontmatter` to use ESM and a default export. I have some local work in progress for [`remark-mdx-code-meta`](https://github.com/remcohaszing/remark-mdx-code-meta) too. This package will follow.

So I agree what you’re proposing is a good idea, but I don’t recommend creating a PR for it, as I would like to combine it with the move to ESM soon, dropping the named export.
